on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Clear Maven Cache
      run: mvn -f junit/pom.xml dependency:purge-local-repository

    - name: Build with Maven
      run: mvn -f junit/pom.xml -B package

    - name: Run JUnit Tests
      run: mvn -f junit/pom.xml test
